version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: utnexamen-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: UTNExamen
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: utnexamen-app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"

volumes:
  db_data:
